[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

[env:esp32dev-test]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -DTEST_MULTI
build_src_filter = +<src/test_multi_strip.cpp>
monitor_speed = 115200
board_build.partitions = huge_app.csv

lib_deps = 
    AsyncTCP
    esp32async/ESPAsyncWebServer
    fauxmoESP
lib_ignore = 
    ESPAsyncTCP
