[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -DTEST_MULTI
board_build.partitions = huge_app.csv
board_build.flash_size = 4MB
